services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: RentBikes
    ports:
      - "5432:5432"
    networks:
      - internal
  api:
    build: .
    depends_on:
      - database
    networks:
      - internal  
networks:
  internal:
    driver: bridge